// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyjpzyhcaeeihgnvszot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5anB6eWhjYWVlaWhnbnZzem90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzM4MDMsImV4cCI6MjA3MTcwOTgwM30.iDN2gm-2yfnhAKh9jszOvXyAQh0wXy0XZPJ6IE3PTB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});